# Generated by Django 4.2.11 on 2024-06-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_profile.entity'),
        ),
        migrations.AddField(
            model_name='author',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_profile.entity'),
        ),
    ]
