# Generated by Django 4.2.11 on 2024-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(max_length=100)),
                ('seo_description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/img/page/')),
                ('image_alt', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('include_astrofont', models.BooleanField(default=False)),
                ('include_math', models.BooleanField(default=False)),
            ],
        ),
    ]
