# Generated by Django 4.2.11 on 2024-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('conference', 'Conference'), ('webinar', 'Webinar'), ('course', 'Course'), ('other', 'Other')], max_length=100)),
                ('image', models.ImageField(upload_to='static/img/event/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('abstract', models.TextField(max_length=150)),
            ],
        ),
    ]
