# Generated by Django 4.2.11 on 2024-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_events', '0003_event_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.CharField(default='example.com', max_length=200),
            preserve_default=False,
        ),
    ]
