# Generated by Django 4.2.11 on 2024-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_events', '0004_event_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seo_description',
            field=models.CharField(default='Some title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title',
            field=models.CharField(default='Some description', max_length=100),
            preserve_default=False,
        ),
    ]
