# Generated by Django 4.2.11 on 2024-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_events', '0005_event_seo_description_event_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(choices=[('oneday', 'One-day event'), ('multiday', 'Multi-day event')], default='oneday', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('hybrid', 'Online & in-person')], default='in_person', max_length=50),
        ),
    ]
