# Generated by Django 4.2.11 on 2024-06-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_events', '0006_event_duration_event_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('hybrid', 'Online & in-person')], default='online', max_length=50),
        ),
    ]
