# Generated by Django 4.2.11 on 2024-06-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_events', '0007_alter_event_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('newbies', 'Newbies in astrology'), ('advanced', 'Advanced astrologers'), ('any', 'Any level')], default='newbies', max_length=50),
        ),
    ]
