# Generated by Django 4.2.11 on 2024-06-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_events', '0008_event_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('newbies', 'Newbies in astrology'), ('advanced', 'Advanced astrologers'), ('any', 'Any level')], default='any', max_length=50),
        ),
    ]
